Optional logging
mbuhot/ecto_job pull request #11
Opened 2018-03-26 20:27 UTC by darksheik

I have another config request - I'd like to be able to disable the logging.  We are up to running tens of thousands of jobs per hour, and we are starting to have to watch how much data we're logging in general because we're sending stuff out to third party log analysis services.

I was on the fence about `disable_logging: true` vs `enable_logging: false`, but it seemed since enabled is the default, it should stay that way.

2018-03-26 23:17 UTC, mbuhot requested changes

2018-03-26 23:17 UTC, mbuhot commented on lib/ecto_job/worker.ex
> +    if Application.get_env(:ecto_job, :disable_logging, false) do
I'd prefer not to have the double-negative of "disable false" here.

I think this reads a bit better for me:
```elixir
if Application.get_env(:ecto_job, :log, true) do
```

Another slightly more complex variant would be to allow configuring the level:

```elixir
Logger.log(Application.get_env(:ecto_job, :logger_level, :info), "#{queue}[#{id}] done: #{duration} µs")
```
[Plug.Logger](https://hexdocs.pm/plug/Plug.Logger.html#module-options) does something similar. Just an idea.

2018-03-26 23:22 UTC, mbuhot commented
> We are up to running tens of thousands of jobs per hour

Wow thats great! 🎉 
You are probably the biggest users of the library :) Would you like commit access?

2018-03-27 13:32 UTC, darksheik commented
Commit access would be wonderful!  I do think PRs are still valuable means of discussing proposed features and will probably still open them when I'd like to bring something in.

I have made your requested changes.  Please check 'em out.
Thanks!

2018-03-27 22:37 UTC, mbuhot approved these changes
👍

2018-03-28 00:31 UTC, merged